dist: bin
before:
  hooks:
    - make deps
    - make verify
builds:
  - main: ./main.go
    binary: "{{ .ProjectName }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X internal.version={{.Version}}"
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
      - darwin
      - openbsd
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - image_templates:
      - "ghcr.io/slamdev/{{ .ProjectName }}:latest"
      - "ghcr.io/slamdev/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/slamdev/{{ .ProjectName }}"
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
changelog:
  skip: false
